### ISSUE TITLE
Inquiry for CPU version or single GPU version

### ISSUE THREAD

**Issue by YeongHyeon** [tae-mo/CRAD#2]
Hi @tae-mo,

Thank you for publishing the excellent research paper and source code.  
- Paper title: Grid-Based Continuous Normal Representation for Anomaly Detection. 
- Model name: Grid Representation for Anomaly Detection (GRAD). 

I am trying to use this code, but I am struggling to run it in my environment (Macbook M1 Chip, w/o GPU) because the multi GPU setting is enabled by default.
Can I ask you to provide the code for a CPU-only or single GPU version?
If you can, the MPS acceleration version will be the best for me.

Thank you for your consideration!

**Comment by cyberblue1** [comment]
Hi!@YeongHyeon
Did you solve the problem? 
I have same issue，how can i fix it?
Thank you for your consideration!

**Comment by YeongHyeon** [comment]
Hi, @cyberblue1 
Yes, I fixed but I do not have the solved version anymore.
One tip for you, find and change all 'cuda' related parts into 'mps' (acceleration device of Apple M chip) computing or 'cpu' computing.
For example, change all `.to('cuda')` parts to `.to('mps')` or `.to('cpu')`.
Good luck to you!
